const { EntitySchema, EntitySchemaOptions } = require("typeorm");

const CompanyModel = new EntitySchema({
    name:"company",
    columns:{
        companyid:{
            type:Number,
            primary:true,
            generated:true,
        },
        companyname:{
            type:String,
            unique:true,
            nullable:false,
        },
        companypan:{
            type:String,
            nullable:false,
            unique:true
        },
        tin:{
            type:String,
            nullable:false,
            unique:true
        },
        vat:{
            type:String,
            nullable:false,
            unique:true
        },
        service_tax_no:{
            type:String,
            nullable:false,
            unique:true
        },
        cst_no:{
            type:String,
            nullable:false,
            unique:true
        },
        phone:{
            type:String,
            nullable:false,
            unique:true
        },
        email:{
            type:String,
            nullable:false,
            unique:true
        },
        website:{
            type:String,
            nullable:false,
            unique:true
        },
        additional_detail:{
            type:String,
            nullable:true
            
        }
    }
})
module.exports = {CompanyModel}