const { EntitySchema } = require("typeorm");

const Product = new EntitySchema({
    name:"product",
    columns:{
        id:{
            type:Number,
            primary:true,
            generated:true
        },
        p_type:{
            type:String,
            nullable:false,
            default:"product"
        },
        uom:{
            type:String,
            default:"box",
            nullable:false,
        },
        sku:{
            type:Number,
            nullable:true
        },
        product_name:{
            type:String,
            nullable:false
        },
        purchase_price:{
            type:Number,
            nullable:true
        },
        hns:{
            type:String,
            nullable:true
        },
        sac:{
            type:String,
            nullable:true
        },
        unit_price:{
            type:Number,
            nullable:true
        },
        tax:{
            type:String,
            default:"1"
        },
        quantity:{
            type:Number,
            nullable:true
        },
        quantity_sold:{
            type:Number,
            default:0,
        },
        cess:{
            type:String,
            nullable:true
        },
        additional:{
            type:String,
            nullable:true
        },
        description:{
            type:String,
            nullable:true
        },

    }
})

module.exports = {Product}